### ISSUE TITLE
Linux1启动错误 【结论：面板对接概率性问题，个人测试正常】

### ISSUE THREAD

**Issue by xiaoku666338** [Misaka-blog/XrayR#13]
- 系统 [ubuntu 20]
 - 架构 [s390x]
 - 面板 [V2board]
 - 协议 [vmess]
 - 版本 [0.8.2.2]

以下是log

May 04 04:02:54 xiaoku systemd[1]: Stopped XrayR Service.
May 04 04:02:54 xiaoku systemd[1]: Started XrayR Service.
May 04 04:02:54 xiaoku systemd[202294]: XrayR.service: Failed to execute command: Exec format error
May 04 04:02:54 xiaoku systemd[202294]: XrayR.service: Failed at step EXEC spawning /usr/local/XrayR/XrayR: Exec format error
May 04 04:02:54 xiaoku systemd[1]: XrayR.service: Main process exited, code=exited, status=203/EXEC
May 04 04:02:54 xiaoku systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 04 04:03:05 xiaoku systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 8185.
May 04 04:03:05 xiaoku systemd[1]: Stopped XrayR Service.
May 04 04:03:05 xiaoku systemd[1]: Started XrayR Service.
May 04 04:03:05 xiaoku systemd[1]: XrayR.service: Main process exited, code=exited, status=203/EXEC
May 04 04:03:05 xiaoku systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by misakano7545** [comment]
@xiaoku666338 使用 xrayr update 命令升级到0.8.2.4

**Comment by xiaoku666338** [comment]
还是一样

May 04 04:12:43 xiaoku systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 8240.
May 04 04:12:43 xiaoku systemd[1]: Stopped XrayR Service.
May 04 04:12:43 xiaoku systemd[1]: Started XrayR Service.
May 04 04:12:43 xiaoku XrayR[209610]: XrayR 0.8.2.4 (A Xray backend that supports many panels)
May 04 04:12:43 xiaoku XrayR[209610]: 2022/05/04 04:12:43 Start the panel..
May 04 04:12:43 xiaoku XrayR[209610]: 2022/05/04 04:12:43 Xray Core Version: 1.5.5
May 04 04:12:43 xiaoku XrayR[209610]: 2022/05/04 04:12:43 [Warning] core: Xray 1.5.5 started
May 04 04:12:43 xiaoku XrayR[209610]: 2022/05/04 04:12:43 Panel Start fialed: request https://www.145140.xyz/api/v1/server/Deepbwork/config failed: {
May 04 04:12:43 xiaoku XrayR[209610]:     "message": "\u8282\u70b9\u4e0d\u5b58\u5728"
May 04 04:12:43 xiaoku XrayR[209610]: }, %!s(<nil>)
May 04 04:12:43 xiaoku XrayR[209610]: panic: Panel Start fialed: request https://www.145140.xyz/api/v1/server/Deepbwork/config failed: {
May 04 04:12:43 xiaoku XrayR[209610]:     "message": "\u8282\u70b9\u4e0d\u5b58\u5728"
May 04 04:12:43 xiaoku XrayR[209610]: }, %!s(<nil>)
May 04 04:12:43 xiaoku XrayR[209610]: goroutine 1 [running]:
May 04 04:12:43 xiaoku XrayR[209610]: log.Panicf({0x1ea9dae, 0x16}, {0xc000743ea8, 0x1, 0x1})
May 04 04:12:43 xiaoku XrayR[209610]:         log/log.go:392 +0xae
May 04 04:12:43 xiaoku XrayR[209610]: github.com/Misaka-blog/XrayR/panel.(*Panel).Start(0xc000107b00)
May 04 04:12:43 xiaoku XrayR[209610]:         github.com/Misaka-blog/XrayR/panel/panel.go:194 +0x2b6
May 04 04:12:43 xiaoku XrayR[209610]: main.main()
May 04 04:12:43 xiaoku XrayR[209610]:         github.com/Misaka-blog/XrayR/main/main.go:92 +0x292
May 04 04:12:43 xiaoku systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 04 04:12:43 xiaoku systemd[1]: XrayR.service: Failed with result 'exit-code'.
