### ISSUE TITLE
http: TLS handshake error from XXXXXXXX:50097: EOF 【结论：GFW扫描服务器、与XrayR无关】

### ISSUE THREAD

**Issue by AllCheeks** [Misaka-blog/XrayR#2]
http: TLS handshake error from XXXXXXXXXX:50097: EOF
请问是怎么回事

**Comment by misakano7545** [comment]
xrayr log
截图看一下

**Comment by AllCheeks** [comment]
并没有影响到使用 所以没有很在意
![Uploading qq.png…]()

**Comment by AllCheeks** [comment]
![qq](https://user-images.githubusercontent.com/56077936/166107526-d737d824-8b64-49ab-b3b9-dc1df642313e.png)

**Comment by misakano7545** [comment]
@AllCheeks xrayr version 看下版本

**Comment by AllCheeks** [comment]
XrayR 版本：XrayR 0.8.2.2 (A Xray backend that supports many panels)

**Comment by crossfw** [comment]
一般来说，这是有人在扫你服务器，或者你用户与你服务器之间有中间人（如果你的用户可以正常使用的话）

**Comment by daycat** [comment]
113.74.*.* 是个gfw探针，不用管

**Comment by Lemonawa** [comment]
=你服务器被gfw扫了
