### ISSUE TITLE
XrayR.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by LeeCenY** [Misaka-blog/XrayR#20]
**描述该错误**
XrayR.service: Failed with result 'exit-code'.

**复现**
wget -N https://raw.githubusercontents.com/Misaka-blog/XrayR-script/master/install.sh && bash install.sh
修改config.yml（确定没修改错）
启动 XrayR

**环境和版本**
 - 系统 [Ubuntu 20.04]
 - 架构 [AMD]
 - 面板 [SSPANEL]
 - 协议 [Trojan]
 - 版本 [0.8.2.2]
 - 部署方式 [例如：一键脚本]

**日志和错误**
`
May 07 21:00:55 22050718083217 systemd[1]: Started XrayR Service.
May 07 21:00:55 22050718083217 XrayR[1101]: XrayR 0.8.0 (A Xray backend that supports many panels)
May 07 21:00:55 22050718083217 XrayR[1101]: 2022/05/07 21:00:55 Start the panel..
May 07 21:00:55 22050718083217 XrayR[1101]: 2022/05/07 21:00:55 Xray Core Version: 1.5.4
May 07 21:00:56 22050718083217 XrayR[1101]: 2022/05/07 21:00:56 [INFO] [xxxxx.com] acme: Obtaining bundled SAN certificate
May 07 21:00:57 22050718083217 XrayR[1101]: 2022/05/07 21:00:57 [INFO] [xxxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/106074393516
May 07 21:00:57 22050718083217 XrayR[1101]: 2022/05/07 21:00:57 [INFO] [xxxxx.com] acme: Could not find solver for: tls-alpn-01
May 07 21:00:57 22050718083217 XrayR[1101]: 2022/05/07 21:00:57 [INFO] [xxxxx.com] acme: use http-01 solver
May 07 21:00:57 22050718083217 XrayR[1101]: 2022/05/07 21:00:57 [INFO] [xxxxx.com] acme: Trying to solve HTTP-01
May 07 21:01:10 22050718083217 XrayR[1101]: 2022/05/07 21:01:10 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/106074393516
May 07 21:01:10 22050718083217 XrayR[1101]: 2022/05/07 21:01:10 Could not obtain certificates:
May 07 21:01:10 22050718083217 XrayR[1101]:         error: one or more domains had a problem:
May 07 21:01:10 22050718083217 XrayR[1101]: [xxxxx.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 103.81.87.81: Fetching http://xxxxx.com/.well-known/acme-challenge/phTANuryTA6pXUxN-6B6BsNwbQwdT3FM3DfQprrrh2w: Timeout during connect (likely firewall problem)
May 07 21:01:10 22050718083217 XrayR[1101]: 2022/05/07 21:01:10 Could not obtain certificates:
May 07 21:01:10 22050718083217 XrayR[1101]:         error: one or more domains had a problem:
May 07 21:01:10 22050718083217 XrayR[1101]: [xxxxx.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 103.81.87.81: Fetching http://xxxxx.com/.well-known/acme-challenge/phTANuryTA6pXUxN-6B6BsNwbQwdT3FM3DfQprrrh2w: Timeout during connect (likely firewall problem)
May 07 21:01:10 22050718083217 XrayR[1101]: panic: Could not obtain certificates:
May 07 21:01:10 22050718083217 XrayR[1101]:         error: one or more domains had a problem:
May 07 21:01:10 22050718083217 XrayR[1101]: [xxxxx.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 103.81.87.81: Fetching http://xxxxx.com/.well-known/acme-challenge/phTANuryTA6pXUxN-6B6BsNwbQwdT3FM3DfQprrrh2w: Timeout during connect (likely firewall problem)
May 07 21:01:10 22050718083217 XrayR[1101]: goroutine 1 [running]:
May 07 21:01:10 22050718083217 XrayR[1101]: log.Panic({0xc00081fd48, 0xc0006e72b0, 0xc00081fd78})
May 07 21:01:10 22050718083217 XrayR[1101]:         log/log.go:354 +0x65
May 07 21:01:10 22050718083217 XrayR[1101]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000563a70)
May 07 21:01:10 22050718083217 XrayR[1101]:         github.com/XrayR-project/XrayR/service/controller/controller.go:52 +0x265
May 07 21:01:10 22050718083217 XrayR[1101]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005220c0)
May 07 21:01:10 22050718083217 XrayR[1101]:         github.com/XrayR-project/XrayR/panel/panel.go:192 +0x543
May 07 21:01:10 22050718083217 XrayR[1101]: main.main()
May 07 21:01:10 22050718083217 XrayR[1101]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
May 07 21:01:10 22050718083217 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 07 21:01:10 22050718083217 systemd[1]: XrayR.service: Failed with result 'exit-code'.
`

**额外的内容**
在这里添加关于问题的任何其他内容

**Comment by LeeCenY** [comment]
之前用你这个脚本就出现这个问题，我就用别人另一个一键脚本没问题，但现在那个一键脚本地址失效，我用回你这个，还是这样问题

**Comment by misakano7545** [comment]
@LeeCenY 放开防火墙端口

**Comment by LeeCenY** [comment]
> @LeeCenY 放开防火墙端口

OK👌🏻
