### ISSUE TITLE
route.json报错

### ISSUE THREAD

**Issue by Error4344** [Misaka-blog/XrayR#22]
DnsConfigPath: /etc/XrayR/main/dns.json
### RouteConfigPath: # /etc/XrayR/main/route.json 
InboundConfigPath: /etc/XrayR/main/custom_inbound.json
OutboundConfigPath: /etc/XrayR/main/custom_outbound.json

### 报错提示：
[root@vultr main]# ./XrayR -config config.yml
XrayR 0.8.2.6 (A Xray backend that supports many panels) 
2022/05/13 17:09:21 Start the panel..
2022/05/13 17:09:21 failed to create instance: app/router: this rule has no effective fields
panic: failed to create instance: app/router: this rule has no effective fields

goroutine 1 [running]:
log.Panicf({0x20d25c2?, 0xc000019980?}, {0xc00050fc08?, 0x1aa99c0?, 0xc00000f0b0?})
        /usr/local/go/src/log/log.go:392 +0x67
github.com/Misaka-blog/XrayR/panel.(*Panel).loadCore(0xc00053fea0?, 0xc0001c4070)
        /etc/XrayR/panel/panel.go:144 +0x9e5
github.com/Misaka-blog/XrayR/panel.(*Panel).Start(0xc00001bb80)
        /etc/XrayR/panel/panel.go:157 +0xe9
main.main()
        /etc/XrayR/main/main.go:92 +0x1ed

----------------------------------------------------------------------------------------------------------------------------
Nodes:
**环境和版本**
 - 系统 [centos7 64]
 - 架构 [AMD64]
 - 面板 [V2board]
 - 内核 [1.5.5]
 - 版本 [0.8.2.6]
 - 部署方式 [手动安装]

**Comment by misakano7545** [comment]
用的是系统自带的route.json并且没配置WARP分流？

**Comment by misakano7545** [comment]
如果是这样的话就按我下面的配置下

```json
{
    "domainStrategy": "IPOnDemand",
    "rules": [
        {
            "type": "field",
            "outboundTag": "block",
            "ip": [
                "geoip:private"
            ]
        },
        {
            "type": "field",
            "outboundTag": "block",
            "protocol": [
                "bittorrent"
            ]
        },
        {
            "type": "field",
            "outboundTag": "IPv6_out",
            "domain": [
                "geosite:netflix"
            ]
        },
        {
            "type": "field",
            "outboundTag": "IPv4_out",
            "network": "udp,tcp"
        }
    ]
}
```

**Comment by Error4344** [comment]
> 如果是这样的话就按我下面的配置下
> 
> ```json
> {
>     "domainStrategy": "IPOnDemand",
>     "rules": [
>         {
>             "type": "field",
>             "outboundTag": "block",
>             "ip": [
>                 "geoip:private"
>             ]
>         },
>         {
>             "type": "field",
>             "outboundTag": "block",
>             "protocol": [
>                 "bittorrent"
>             ]
>         },
>         {
>             "type": "field",
>             "outboundTag": "IPv6_out",
>             "domain": [
>                 "geosite:netflix"
>             ]
>         },
>         {
>             "type": "field",
>             "outboundTag": "IPv4_out",
>             "network": "udp,tcp"
>         }
>     ]
> }
> ```

### 问题已解决
