### ISSUE TITLE
XrayR.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by AaronYES** [Misaka-blog/XrayR#23]
**描述该错误**
XrayR.service: Failed with result 'exit-code'.

**复现**
使用一键脚本安装
`wget -N https://raw.githubusercontents.com/Misaka-blog/XrayR-script/master/install.sh && bash install.sh`
修改config文件 执行 XrayR restart 
XrayR可能启动失败，请稍后使用 XrayR log 查看日志信息

**环境和版本**
 - 系统 [例如：Debian 11]
 - 架构 [例如：AMD64]
 - 面板 [例如：V2board]
 - 协议 [例如：vmess]
 - 版本 [例如：0.8.2.6]
 - 部署方式 [例如：一键脚本]

**日志和错误**
May 16 06:43:53 unspecified systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 64.
May 16 06:43:53 unspecified systemd[1]: Stopped XrayR Service.
May 16 06:43:53 unspecified systemd[1]: Started XrayR Service.
May 16 06:43:53 unspecified XrayR[313276]: XrayR 0.8.2.6 (A Xray backend that supports many panels)
May 16 06:43:53 unspecified XrayR[313276]: 2022/05/16 06:43:53 Start the panel..
May 16 06:43:53 unspecified XrayR[313276]: 2022/05/16 06:43:53 Xray Core Version: 1.5.5
May 16 06:43:53 unspecified XrayR[313276]: 2022/05/16 06:43:53 [Warning] core: Xray 1.5.5 started
May 16 06:43:54 unspecified XrayR[313276]: panic: runtime error: index out of range [0] with length 0
May 16 06:43:54 unspecified XrayR[313276]: goroutine 1 [running]:
May 16 06:43:54 unspecified XrayR[313276]: github.com/Misaka-blog/XrayR/service/controller.(*Controller).addNewUser(0xc0001400a0, 0xc00074fec0, 0xc00061fd68?)
May 16 06:43:54 unspecified XrayR[313276]:         github.com/Misaka-blog/XrayR/service/controller/controller.go:339 +0x2cf
May 16 06:43:54 unspecified XrayR[313276]: github.com/Misaka-blog/XrayR/service/controller.(*Controller).Start(0xc0001400a0)
May 16 06:43:54 unspecified XrayR[313276]:         github.com/Misaka-blog/XrayR/service/controller/controller.go:64 +0x2a9
May 16 06:43:54 unspecified XrayR[313276]: github.com/Misaka-blog/XrayR/panel.(*Panel).Start(0xc000023900)
May 16 06:43:54 unspecified XrayR[313276]:         github.com/Misaka-blog/XrayR/panel/panel.go:192 +0x59a
May 16 06:43:54 unspecified XrayR[313276]: main.main()
May 16 06:43:54 unspecified XrayR[313276]:         github.com/Misaka-blog/XrayR/main/main.go:92 +0x1ed
May 16 06:43:54 unspecified systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 06:43:54 unspecified systemd[1]: XrayR.service: Failed with result 'exit-code'.

**额外的内容**
手里有两个面板 一个 最新版本的v2b 一个是1.5.4版本的v2b 两个面板用的一个域名的不同二级域名 当我修改confiig为 老板1.5.4面板就没有问题 对接新版本v2b 就出问题了

**Comment by misakano7545** [comment]
@AaronYES 新版本是dev分支的？

**Comment by AaronYES** [comment]
我使用之前vps上提取的0.7.5、0.8.0旧版本 可以正常运行 应该是跟v2b无关
暂时不折腾了
