### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by hc4620303** [Misaka-blog/XrayR#31]
![image](https://user-images.githubusercontent.com/22239425/172598791-e94aa828-ee9c-45be-a17c-f4f4225435a1.png)

**Comment by 07031218** [comment]
在v2board面板添加配置好相关订阅即可解决。

**Comment by hc4620303** [comment]
> 在v2board面板中添加配置好相关订阅即可解决。
设置好了的 订阅一直没改过 我用1.5.2版本就没问题 昨天都还好好的 今天重启一下节点就启不起来了

**Comment by 07031218** [comment]
> > 在v2board面板中添加配置好相关订阅即可解决。
> > 设置好了的 订阅一直没改过 我用1.5.2版本就没问题 昨天都还好好的 今天重启一下节点就启不起来了

那就不清楚了，今天我碰到和你同样的问题，后来配置好订阅后就没报错了。
