### ISSUE TITLE
[BUG] 流量、在线信息上报失败

### ISSUE THREAD

**Issue by AMAU1126** [Misaka-blog/XrayR#38]
**描述该错误**
流量跟在线信息都上报失败，在面板日志中看到是 用Get上报的，目前面板接口是使用Post

**复现**
复现该bug的步骤

**环境和版本**
 - 系统 CentOS 7.9
 - 架构 amd64
 - 面板 PMPanel
 - 协议 none
 - 版本 0.8.2.6
 - 部署方式 手动

**日志和错误**
请使用`xrayr log`查看并添加日志，以帮助解释你的问题
2022/06/21 02:04:26 request http://baidu.com/api/traffic failed: {"timestamp":"2022-06-21 10:04:26","status":405,"error":"Method Not Allowed","message":"","path":"/api/traffic"}, %!s(<nil>)
2022/06/21 02:04:26 request http://baidu.com/api/online failed: {"timestamp":"2022-06-21 10:04:26","status":405,"error":"Method Not Allowed","message":"","path":"/api/online"}, %!s(<nil>)
**额外的内容**
在这里添加关于问题的任何其他内容
![图片](https://user-images.githubusercontent.com/96520210/174701193-87db565d-8e0d-4b75-8870-f077a35ac19c.png)
Nginx 日志
```
0.0.0.0 - - [21/Jun/2022:10:04:26 +0800] "GET /api/traffic HTTP/1.1" 405 123 "http://baidu.com/api/traffic" "go-resty/2.7.0 (https://github.com/go-resty/resty)"
0.0.0.0 - - [21/Jun/2022:10:04:26 +0800] "GET /api/online HTTP/1.1" 405 122 "http://baidu.com/api/online" "go-resty/2.7.0 (https://github.com/go-resty/resty)"

```

**Comment by misakano7545** [comment]
@AMAU1126 PMPanel 什么版本？

**Comment by misakano7545** [comment]
看起来你这好像是被防火墙拦截了，试试看把vps的ip加上白名单

**Comment by AMAU1126** [comment]
> 看起来你这好像是被防火墙拦截了，试试看把vps的ip加上白名单

不是防火墙，获取节点信息能正常获取到，获取用户信息也能获取到。你看一下XrayR 哪个上报接口，是不是使用GET发的请求。

**Comment by crossfw** [comment]
@AMAU1126 https://github.com/Misaka-blog/XrayR/blob/master/api/pmpanel/pmpanel.go#L300 
程序使用了POST 是不是面板更新了

**Comment by AMAU1126** [comment]
> @AMAU1126 https://github.com/Misaka-blog/XrayR/blob/master/api/pmpanel/pmpanel.go#L300 程序使用了POST 是不是面板更新了

面板是POST接口，但是不知道为啥到Nginx是Get

**Comment by crossfw** [comment]
@AMAU1126 Nginx反代问题

**Comment by AMAU1126** [comment]
> @AMAU1126 Nginx反代问题

好，我去看看。

**Comment by AMAU1126** [comment]
Nginx转发问题，问题已解决！
